source "https://rubygems.org"

ruby "3.1.4"

# Core framework
gem "sinatra", "~> 4.0"
gem "sinatra-contrib", "~> 4.0"

# Database
gem "sqlite3", "~> 1.4"
gem "activerecord", "~> 7.0"
gem "sinatra-activerecord", "~> 2.0"

# JSON handling
gem "multi_json", "~> 1.15"

# CORS support
gem "rack-cors", "~> 2.0"

# Web server
gem "puma", "~> 5.6"
gem "rackup", "~> 2.1"
gem "webrick", "~> 1.7"

group :development do
  gem "rake", "~> 13.0"
end
